// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjoyagsyZCEpJVNT50SARxTfhRUbUyFsc',
    appId: '1:294224939799:web:77ce5503d6b5eabe8f4552',
    messagingSenderId: '294224939799',
    projectId: 'mysimtek-pelanggan',
    authDomain: 'mysimtek-pelanggan.firebaseapp.com',
    storageBucket: 'mysimtek-pelanggan.firebasestorage.app',
    measurementId: 'G-QWZ95YX33P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0xuVlMTX5h_HEmaHvCXh7psfohaJkcCQ',
    appId: '1:294224939799:android:44449974632c8f8b8f4552',
    messagingSenderId: '294224939799',
    projectId: 'mysimtek-pelanggan',
    storageBucket: 'mysimtek-pelanggan.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB67MSvB2Bp9X-SVEsJyltlCFkt1pf-XK0',
    appId: '1:294224939799:ios:16963a35fe3266648f4552',
    messagingSenderId: '294224939799',
    projectId: 'mysimtek-pelanggan',
    storageBucket: 'mysimtek-pelanggan.firebasestorage.app',
    iosBundleId: 'com.mysimtek.teknisi.mysimtekTeknisi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB67MSvB2Bp9X-SVEsJyltlCFkt1pf-XK0',
    appId: '1:294224939799:ios:16963a35fe3266648f4552',
    messagingSenderId: '294224939799',
    projectId: 'mysimtek-pelanggan',
    storageBucket: 'mysimtek-pelanggan.firebasestorage.app',
    iosBundleId: 'com.mysimtek.teknisi.mysimtekTeknisi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjoyagsyZCEpJVNT50SARxTfhRUbUyFsc',
    appId: '1:294224939799:web:50bbd4577f4e3b318f4552',
    messagingSenderId: '294224939799',
    projectId: 'mysimtek-pelanggan',
    authDomain: 'mysimtek-pelanggan.firebaseapp.com',
    storageBucket: 'mysimtek-pelanggan.firebasestorage.app',
    measurementId: 'G-4QXRL9F7TQ',
  );
}
